apiVersion: v1	
kind: Service	
metadata:
  name: enigmabbs-svc   # < name of the persistant volume claim ("pvc'")
  namespace: enigmabbs  
spec:	
  ports:	
  - port: 8888	
    name: telnet
    targetPort: 8888
  - port: 8889	
    name: ssh
    targetPort: 8889
  type: NodePort
  selector:	
    app: enigmabbs